# Generated by Django 5.0 on 2024-01-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='night_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
