# Generated by Django 5.0 on 2024-01-01 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_finance', '0002_alter_room_night_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='night_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
